"""migrate-20252112004303

Revision ID: 34c22727e75f
Revises: d0eb39ae79c4
Create Date: 2025-12-21 00:43:04.257210

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '34c22727e75f'
down_revision: Union[str, None] = 'd0eb39ae79c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('certificate_ibfk_3', 'certificate', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('certificate_ibfk_3', 'certificate', 'course', ['additional_course_id'], ['id'])
    # ### end Alembic commands ###
