"""migrate-20251903113003

Revision ID: 3ab53535ced8
Revises: 43c6273d8763
Create Date: 2025-03-19 11:30:03.728182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ab53535ced8'
down_revision: Union[str, None] = '43c6273d8763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('certificate_version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'certificate_version')
    # ### end Alembic commands ###
