"""migrate-20250902032947

Revision ID: 43c6273d8763
Revises: f66f0c226b47
Create Date: 2025-02-09 03:29:47.985863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43c6273d8763'
down_revision: Union[str, None] = 'f66f0c226b47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate', sa.Column('course_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'certificate', 'course', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'certificate', type_='foreignkey')
    op.drop_column('certificate', 'course_id')
    # ### end Alembic commands ###
