"""migrate-20250802162230

Revision ID: 7a67be6c72f5
Revises: 002e8665bb1f
Create Date: 2025-02-08 16:22:32.539192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a67be6c72f5'
down_revision: Union[str, None] = '002e8665bb1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale_person',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=200), nullable=False),
    sa.Column('lastname', sa.VARCHAR(length=200), nullable=False),
    sa.Column('reference_code', sa.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.VARCHAR(length=200), nullable=False),
    sa.Column('firstname_th', sa.VARCHAR(length=200), nullable=False),
    sa.Column('lastname_th', sa.VARCHAR(length=200), nullable=False),
    sa.Column('firstname_en', sa.VARCHAR(length=200), nullable=False),
    sa.Column('lastname_en', sa.VARCHAR(length=200), nullable=False),
    sa.Column('sale_person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sale_person_id'], ['sale_person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('sale_person')
    # ### end Alembic commands ###
