"""migrate-20251004110505

Revision ID: 8c04f675cb24
Revises: ecd1c5c6779f
Create Date: 2025-04-10 11:05:05.527280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8c04f675cb24'
down_revision: Union[str, None] = 'ecd1c5c6779f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.add_column('users', sa.Column('google_uid', sa.VARBINARY(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'google_uid')
    op.alter_column('student', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
