"""migrate-20252112003923

Revision ID: d0eb39ae79c4
Revises: 4c7bdc2f448f
Create Date: 2025-12-21 00:39:24.178707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0eb39ae79c4'
down_revision: Union[str, None] = '4c7bdc2f448f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate', sa.Column('additional_course_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'certificate', 'course', ['additional_course_id'], ['id'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'certificate', type_='foreignkey')
    op.drop_column('certificate', 'additional_course_id')
    # ### end Alembic commands ###
