"""migrate-20250704172105

Revision ID: ecd1c5c6779f
Revises: 5d48cba98122
Create Date: 2025-04-07 17:21:06.116713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecd1c5c6779f'
down_revision: Union[str, None] = '5d48cba98122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'student', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_column('student', 'user_id')
    # ### end Alembic commands ###
